### ISSUE TITLE
Use transclude to allow custom views

### ISSUE THREAD

**Issue by pdorgambide** [alalonde/angular-multi-select#1]
Great job!!!, Awesome directive. 
An issue to get it more flexible will be allow custom views for items (using transclusion)

<div multi-select>
  
</div>

I hope could be usefull.

**Comment by alalonde** [comment]
Hello, thanks for the feedback.  Another solution would be to extract the template from the directive and put it in the $templateCache so that it can easily overridden, such as in angular-ui-bootstrap.  

Additionally, I could extract the <label class="checkbox"> into its own directive which would be automatically included by its parent.  Let me know if either option would be preferable and I will implement it.
